name: sherlock-holmes-learning-app
region: nyc
services:
  - name: web
    dockerfile_path: Dockerfile
    source_dir: .
    github:
      branch: main
      deploy_on_push: true
    health_check:
      http_path: /health
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-s
    routes:
      - path: /
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: REDIS_URL
        scope: RUN_TIME
        value: ${redis.REDIS_URL}
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: JWT_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: MODEL_NAME
        scope: RUN_TIME
        value: "gpt-4o-mini"
      - key: ENVIRONMENT
        scope: RUN_TIME
        value: "production"
      - key: DEBUG
        scope: RUN_TIME
        value: "false"
      - key: CORS_ORIGINS
        scope: RUN_TIME
        value: ${APP_URL}
databases:
  - name: db
    engine: PG
    production: true
    cluster_name: sherlock-app-db
    db_name: sherlock_db
    db_user: sherlock_admin
  - name: redis
    engine: REDIS
    production: true
    version: "7" 