"""Add character_id and language_level to journey/story sessions

Revision ID: 8d7e626c9ff9
Revises: merge_heads
Create Date: 2025-04-27 19:01:56.096668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d7e626c9ff9'
down_revision: Union[str, None] = 'merge_heads'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('story_hints')
    op.drop_index('ix_story_messages_message_id', table_name='story_messages')
    op.drop_table('story_messages')
    op.drop_table('penpal_letters')
    op.drop_index('ix_sandbox_messages_message_id', table_name='sandbox_messages')
    op.drop_table('sandbox_messages')
    op.drop_index('ix_sandbox_sessions_user_id', table_name='sandbox_sessions')
    op.drop_table('sandbox_sessions')
    op.drop_table('message_processing')
    op.add_column('journey_sessions', sa.Column('character_id', sa.String(), nullable=True))
    op.add_column('journey_sessions', sa.Column('language_level', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journey_sessions', 'language_level')
    op.drop_column('journey_sessions', 'character_id')
    op.create_table('story_sessions',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('language_level', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='story_sessions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='story_sessions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_story_sessions_user_id', 'story_sessions', ['user_id'], unique=False)
    op.create_table('message_processing',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('original_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('corrected_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_appropriate', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('inappropriate_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('grammar_feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('feature', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='message_processing_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='message_processing_pkey')
    )
    op.create_table('sandbox_messages',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('message_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sandbox_sessions.id'], name='sandbox_messages_session_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sandbox_messages_pkey')
    )
    op.create_index('ix_sandbox_messages_message_id', 'sandbox_messages', ['message_id'], unique=False)
    op.create_table('penpal_letters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('letter_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('response_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('character_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('delivery_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='penpal_letters_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='penpal_letters_pkey')
    )
    op.create_table('sandbox_sessions',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='sandbox_sessions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sandbox_sessions_pkey')
    )
    op.create_index('ix_sandbox_sessions_user_id', 'sandbox_sessions', ['user_id'], unique=False)
    op.create_table('story_hints',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['story_messages.id'], name='story_hints_message_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['story_sessions.id'], name='story_hints_session_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='story_hints_pkey')
    )
    op.create_table('story_messages',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('message_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['story_sessions.id'], name='story_messages_session_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='story_messages_pkey')
    )
    op.create_index('ix_story_messages_message_id', 'story_messages', ['message_id'], unique=False)
    # ### end Alembic commands ###
