"""create_initial_tables

Revision ID: 970b6c9d92f6
Revises: 4d424ef7c613
Create Date: 2025-04-28 13:32:14.908710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '970b6c9d92f6'
down_revision: Union[str, None] = None # This is the very first migration
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands manually created based on auth/models.py ###
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=80), nullable=False),
        sa.Column('password_hash', sa.String(length=256), nullable=True),
        sa.Column('email', sa.String(length=120), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('first_name', sa.String(length=80), nullable=True),
        sa.Column('last_name', sa.String(length=80), nullable=True),
        sa.Column('role', sa.String(length=20), nullable=True),
        sa.Column('student_id', sa.String(length=80), nullable=True),
        sa.Column('grade', sa.String(length=20), nullable=True),
        sa.Column('section', sa.String(length=20), nullable=True),
        sa.Column('subject', sa.String(length=80), nullable=True),
        sa.Column('phone', sa.String(length=20), nullable=True),
        sa.Column('temp_password', sa.String(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True), # Using server_default for now()
        sa.PrimaryKeyConstraint('id')
    )
    # Add indexes separately as good practice
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_student_id'), 'users', ['student_id'], unique=False)

    # Note: This is a basic creation. If other tables are needed before
    # c975de9d868b, they should be added here too. For now, focusing on the 'users' dependency.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_student_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
